import Head from "next/head";
import { MainLayout, LeftSidebar, RightSidebar } from "@/components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ngab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <LeftSidebar />
        <div className="w-1/3">
          <p>Ngab</p>
        </div>
        <RightSidebar />
      </MainLayout>
    </>
  );
}
